import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type Request = { id: string; service: string; amount: number; decision: string; status: string; reason: string; x402_status: string; transaction_id?: string | null; created_at: string };
type Dashboard = { agent: { id: string; name: string; status: string }; budget: number; spent: number; remaining: number; approved: number; blocked: number; pending: number; requests: Request[] };
type Risk = { agent: { id: string; name: string; walletAddress: string; status: string }; riskScore: number; riskLevel: string; factors: { name: string; impact: number; explanation: string }[]; budget: { remainingMicros: number; dailyLimitMicros: number; dailyUsedMicros: number; dailyRemainingMicros: number; monthlyLimitMicros: number; monthlyUsedMicros: number; monthlyRemainingMicros: number; allowedCategories: string[] }; recentActivity: { blockedRequests: number; approvalRequests: number; failedPayments: number; requestsLast24Hours: number } };
const services = [{ service: "Weather API", category: "weather", amount: 0.005, note: "Auto-approve policy" }, { service: "Data API", category: "data", amount: 0.02, note: "Human approval policy" }, { service: "Premium research API", category: "research", amount: 0.5, note: "Blocked by category policy" }];
const usd = (n: number) => `$${n.toFixed(n < 0.01 ? 3 : 2)}`;
const status = (value: string) => value.replace(/_/g, " ");
const cls = (value: string) => value.toLowerCase().replace(/_/g, "-");
const explorer = (id: string) => `https://testnet.explorer.perawallet.app/tx/${id}/`;
function Badge({ value }: { value: string }) { return <span className={`badge ${cls(value)}`}>{status(value)}</span>; }

function App() {
  const [data, setData] = useState<Dashboard | null>(null); const [risk, setRisk] = useState<Risk | null>(null); const [message, setMessage] = useState("Ready to evaluate agent spend.");
  const refresh = async () => { const dashboard = await fetch("/api/dashboard").then(r => r.json()) as Dashboard; setData(dashboard); setRisk(await fetch(`/api/agents/${dashboard.agent.id}/risk`).then(r => r.json()) as Risk); };
  useEffect(() => { void refresh(); }, []);
  const utilization = useMemo(() => data ? Math.min(100, data.spent / data.budget * 100) : 0, [data]);
  async function submit(service: typeof services[number]) { const created = await fetch("/api/payment-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ agentId: "agent-atlas", ...service }) }); const result = await created.json(); if (!created.ok) { setMessage(result.error); return; } if (result.decision === "APPROVED") { setMessage("APPROVED - Entering x402 payment stage..."); const execution = await fetch(`/api/payment-requests/${result.id}/execute`, { method: "POST" }); const settled = await execution.json(); setMessage(settled.x402Status === "SETTLED" ? `SETTLED - Algorand transaction ${settled.transactionId}` : `${settled.x402Status ?? "PAYMENT FAILED"} - ${settled.error ?? "Payment did not settle."}`); } else setMessage(`${status(result.decision)} - ${result.reason}`); await refresh(); }
  async function approve(id: string) { const result = await fetch(`/api/payment-requests/${id}/approve`, { method: "POST" }).then(r => r.json()); setMessage(result.x402Status === "SETTLED" ? `APPROVED -> SETTLED - Algorand transaction ${result.transactionId}` : result.error ?? "Payment did not settle."); await refresh(); }
  async function copyWallet() { if (risk) { await navigator.clipboard.writeText(risk.agent.walletAddress); setMessage("Wallet address copied to clipboard."); } }
  if (!data) return <main className="loading">Loading PolicyPay...</main>;
  const queued = data.requests.filter(r => r.status === "REQUIRES_APPROVAL"); const settled = data.requests.filter(r => r.x402_status === "SETTLED"); const total = Math.max(1, data.approved + data.pending + data.blocked);
  return <main><header className="hero"><div><p className="eyebrow">POLICYPAY</p><h1>PolicyPay</h1><p className="subtitle">AI Spend Governance with x402 & Algorand</p></div><div className="agent"><i /> <div><b>{data.agent.name}</b><small>Agent status - {data.agent.status}</small></div></div></header>
    <section className="cards"><Card label="Operating allowance" value={usd(data.budget)} detail="All-time agent allocation" /><Card label="Settled spend" value={usd(data.spent)} detail={`${utilization.toFixed(1)}% of operating allowance`} /><Card label="Remaining allowance" value={usd(data.remaining)} detail="Allocation less real settlements" /><Card label="Policy outcomes" value={`${data.approved} / ${data.pending} / ${data.blocked}`} detail="approved - pending - blocked" /></section>
    <section className="analytics"><div className="panel"><div className="section-heading"><div><p className="section-kicker">OPERATING ALLOWANCE</p><h2>Settled spend runway</h2></div><strong>{utilization.toFixed(1)}%</strong></div><div className="runway"><span style={{ width: `${utilization}%` }} /></div><div className="runway-labels"><span>{usd(data.spent)} settled</span><span>{usd(data.remaining)} allowance remaining</span></div></div><div className="panel"><p className="section-kicker">POLICY ACTIVITY</p><h2>Decision mix</h2><Decision label="Approved" value={data.approved} total={total} type="approved" /><Decision label="Requires approval" value={data.pending} total={total} type="requires-approval" /><Decision label="Blocked" value={data.blocked} total={total} type="blocked" /></div></section>
    {risk && <section className="passport panel"><div className="section-heading"><div><p className="section-kicker">AGENT PASSPORT</p><h2>{risk.agent.name}</h2><small>{risk.agent.id} - <b>{risk.agent.status}</b></small></div><Badge value={`${risk.riskLevel}_RISK`} /></div><div className="passport-grid"><div className="score"><div style={{ background: `conic-gradient(${risk.riskLevel === "LOW" ? "#63d7b5" : risk.riskLevel === "MEDIUM" ? "#f6b760" : "#ed7883"} ${risk.riskScore * 3.6}deg,#172942 0)` }}><b>{risk.riskScore}</b><small>/ 100</small></div><span>Deterministic risk score</span></div><div className="passport-info"><p>Algorand wallet</p><b>{risk.agent.walletAddress.slice(0, 8)}...{risk.agent.walletAddress.slice(-6)}</b><button onClick={copyWallet}>Copy</button><div className="metrics"><Metric label="Daily settled spend" value={`${usd(risk.budget.dailyUsedMicros / 1e6)} / ${usd(risk.budget.dailyLimitMicros / 1e6)}`} /><Metric label="Remaining today" value={usd(risk.budget.dailyRemainingMicros / 1e6)} /><Metric label="Monthly settled spend" value={`${usd(risk.budget.monthlyUsedMicros / 1e6)} / ${usd(risk.budget.monthlyLimitMicros / 1e6)}`} /><Metric label="Remaining this month" value={usd(risk.budget.monthlyRemainingMicros / 1e6)} /></div><p>Allowed categories</p><div className="categories">{risk.budget.allowedCategories.map(x => <span key={x}>OK {x}</span>)}</div></div><div className="factors"><p>WHY THIS SCORE</p>{risk.factors.map(f => <div key={f.name}><i className={f.impact ? "hit" : "clear"}>{f.impact ? "!" : "OK"}</i><span><b>{f.name}{f.impact ? ` +${f.impact}` : ""}</b><small>{f.explanation}</small></span></div>)}</div></div><div className="behavior"><span><b>{risk.recentActivity.blockedRequests}</b> blocked requests</span><span><b>{risk.recentActivity.approvalRequests}</b> approval requests</span><span><b>{risk.recentActivity.failedPayments}</b> failed payments</span><span><b>{risk.recentActivity.requestsLast24Hours}</b> requests / 24h</span></div></section>}
    <section className="grid"><div className="panel"><p className="section-kicker">DEMO CONSOLE</p><h2>Simulate agent spend</h2><p className="muted">Policy is evaluated on the backend before x402 payment.</p>{services.map(s => <button className="service" key={s.service} onClick={() => submit(s)}><span><b>{s.service}</b><small>{s.category} - {s.note}</small></span><strong>{usd(s.amount)} -&gt;</strong></button>)}<p className="notice">* {message}</p></div><div className="panel"><div className="section-heading"><div><p className="section-kicker">HUMAN REVIEW</p><h2>Approval queue</h2></div><b>{queued.length}</b></div>{queued.length ? queued.map(r => <div className="queue" key={r.id}><span><b>{r.service}</b><small>{usd(r.amount)} - {r.reason}</small></span><button onClick={() => approve(r.id)}>Approve</button></div>) : <p className="empty">OK No requests awaiting review.</p>}</div></section>
    <section className="panel activity"><div className="section-heading"><div><p className="section-kicker">AUDIT TRAIL</p><h2>Decision & payment activity</h2></div><span>{settled.length} settled on TestNet</span></div><div className="table-wrap"><table><thead><tr><th>Service request</th><th>Amount</th><th>Decision</th><th>x402 status</th><th>Algorand transaction</th></tr></thead><tbody>{data.requests.map(r => <tr key={r.id}><td><b>{r.service}</b><small>{r.reason}</small></td><td>{usd(r.amount)}</td><td><Badge value={r.decision} /></td><td><Badge value={r.x402_status} /></td><td>{r.transaction_id ? <a className="tx" href={explorer(r.transaction_id)} target="_blank" rel="noreferrer">{r.transaction_id.slice(0, 10)}...{r.transaction_id.slice(-6)} -&gt;</a> : "-"}</td></tr>)}</tbody></table></div></section></main>;
}
function Card({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="card"><p>{label}</p><strong>{value}</strong><small>{detail}</small></div>; }
function Decision({ label, value, total, type }: { label: string; value: number; total: number; type: string }) { return <div className="decision"><span>{label}<b>{value}</b></span><i><em className={type} style={{ width: `${value / total * 100}%` }} /></i></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><small>{label}</small><b>{value}</b></div>; }
createRoot(document.getElementById("root")!).render(<App />);
